version: "3"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - network1
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack-server:latest
    networks:
      - network1
    ports:
      - "6379:6379"
    volumes:
      - ~/.redis-stack-data:/data
networks:
  dev_default:
  network1:
    name: project_default
    external: true
