version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    network_mode: host
    volumes:
      - ~/.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack-server:latest
    network_mode: host
    volumes:
      - ~/.redis-stack-data:/data
