trigger:
  branches:
    include:
      - develop
      - main
  paths:
    exclude:
      - .github
      - .husky
      - docs
      - pipelines
      - ENV.md
      - README.md
pr:
  branches:
    include:
      - '*'
resources:
  repositories:
    - repository: lp-base
      type: github
      endpoint: AcertaAnalyticsSolutions_GitHub
      name: AcertaAnalyticsSolutions/lp-base
variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - template: pipelines/develop-vars.yaml@lp-base
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'main') }}:
      - template: pipelines/qas-vars.yaml@lp-base
  - ${{ else }}:
      - template: pipelines/pr-vars.yaml@lp-base
stages:
  - template: pipelines/ci-test-shell-template.yml@lp-base
    parameters:
      testRunnerImageName: node:18-bullseye
      postgresImageName: postgres:15
      sshRepositoryKeyEnabled: true
  - template: pipelines/azure-pipelines-with-ssh-template.yaml@lp-base
    parameters:
      imageRepository: "nestjs-example"
      tag: "$(Build.SourceVersion)"
      dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
      sourceBranchName: "$(Build.SourceBranchName)"
      push: ${{ variables.push }}
      environment: ${{ variables.environment }}
      dockerRegistryServiceConnection: ${{ variables.dockerRegistryServiceConnection }}
