trigger:
  branches:
    include:
      - develop
      - main
  paths:
    exclude:
      - docs
      - pipelines
      - .git_commit.json
      - azure-pipelines.y*ml
      - azure-pipelines-qas.y*ml
pr:
  branches:
    include:
      - feature/*
      - hotfix/*
      - bugfix/*
resources:
  repositories:
    - repository: lp-base
      type: github
      endpoint: AcertaAnalyticsSolutions_GitHub
      name: AcertaAnalyticsSolutions/lp-base
variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - template: pipelines/develop-vars.yaml@lp-base
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'main') }}:
      - template: pipelines/qas-vars.yaml@lp-base
  - ${{ else }}:
      - template: pipelines/pr-vars.yaml@lp-base
stages:
  - template: pipelines/ci-test-shell-template.yml@lp-base
    parameters:
      testRunnerImageName: node:18-bullseye
      postgresImageName: postgres:15
      sshRepositoryKeyEnabled: true
      unitTestEnabled: true
      serviceTestEnabled: false
  - template: pipelines/azure-pipelines-with-ssh-template.yaml@lp-base
    parameters:
      imageRepository: "nestjs-example"
      tag: "$(Build.SourceVersion)"
      dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
      sourceBranchName: "$(Build.SourceBranchName)"
      push: ${{ variables.push }}
      environment: ${{ variables.environment }}
      dockerRegistryServiceConnection: ${{ variables.dockerRegistryServiceConnection }}
