prd:
  info:
    redact:
      - "req.headers.Authorization"
      - 'req.headers["X-Api-Key"]'
      - "req.headers.authorization"
      - "req.headers.cookie"
      - "res.headers.authorization"
      - "res.headers.cookie"
      - "res.body.password"
  debug:
    redact:
      - "req.headers.Authorization"
      - "req.headers.authorization"
      - "req.headers.cookie"
      - "res.headers.authorization"
      - "res.headers.cookie"
      - "res.body.password"
  trace:
    redact:
      - "req.headers.Authorization"
      - "req.headers.authorization"
      - "req.headers.cookie"
      - "res.headers.authorization"
      - "res.headers.cookie"
      - "res.body.password"
dev:
  trace:
    redact:
      - "req.headers.Authorization"
      - 'req.headers["X-Api-Key"]'
      - "req.headers.cookie"
      - "res.headers.authorization"
      - "res.headers.cookie"
      - "res.body.password"
